#!/bin/bash

dir=$(dirname "$(realpath $0)")
cp ${dir}/snowflaker /usr/local/bin/

printf "\e[32mInstalling snowflaker...\n"
count=0
while [ $count -lt 6 ]; do
  printf "\e[32\.\e[0m"
  let count=count+1
  sleep 1
done
echo
printf "Done! You may now use snowflaker from any directory by typing
\"snowflaker\" in terminal\e[0m\n"
echo
printf "This script will self-destruct in 5 seconds"
count=0
while [ $count -lt 6 ]; do
  printf "\e[32\.\e[0m"
  let count=count+1
  sleep 1
done
echo
printf "\e[32m    .( * .\n"
printf " .*  .  ) .\n"
printf ". . POOF .* .\n"
printf " '* . (  .) '\n"
printf "  \` ( . *\e[0m\n"

