#!/usr/bin/env python

import sys
import os
import shutil
import csv

dir_name = os.path.dirname(os.path.abspath(__file__))
arg = ''

if len(sys.argv) > 1:
    arg = sys.argv[1]

with open('snowflakes.csv', mode='r') as infile:
    reader = csv.reader(infile)
    snowflake_map = dict((rows[0],rows[1]) for rows in reader)

def convert():
    for file in os.listdir("."):
        if file in ['snowflaker', 'snowflakes.csv']:
            continue
        file_parts = file.split('.')
        filename = file_parts[0]
        ext = file_parts[1]
        if filename in snowflake_map:
            new_name = snowflake_map[filename] + '.' + ext
            print "\033[1;32mSnowflakerizing!\033[1;0m", " %s -----> %s" %(file, new_name)
            os.rename(file, new_name)
        else:
            print "Skipping %s: Not in list of acceptable snowflakes or already snowflakerized" % file

def undo():
    for file in os.listdir("."):
        if file in ['snowflaker', 'snowflakes.csv']:
            continue
        file_parts = file.split('.')
        filename = file_parts[0]
        ext = file_parts[1]
        if filename in snowflake_map.values():
            for origin in snowflake_map:
                if snowflake_map[origin] == filename:
                    new_name = origin + '.' + ext
                    print "\033[1;32mResetting\033[1;0m", " %s -----> %s" %(file, new_name)
                    os.rename(file, new_name)
        else:
            print "Skipping %s: Not a snowflake" % file

if arg == 'undo':
    undo()
else:
    convert()

