#!/bin/bash

rm /usr/local/bin/snowflaker

printf "\e[32mUninstalling snowflaker...\n"
count=0
while [ $count -lt 6 ]; do
  printf "\e[32\.\e[0m"
  let count=count+1
  sleep 1
done
echo
printf "Done! Snowflaker has been successfully uninstalled\e[0m\n"
echo
printf "This script will self-destruct in 5 seconds"
count=0
while [ $count -lt 6 ]; do
  printf "\e[32\.\e[0m"
  let count=count+1
  sleep 1
done
echo
printf "\e[32m    .( * .\n"
printf " .*  .  ) .\n"
printf ". . POOF .* .\n"
printf " '* . (  .) '\n"
printf "  \` ( . *\e[0m\n"

